// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: edr/v1/agent.proto

package edrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_Heartbeat_FullMethodName      = "/edr.v1.AgentService/Heartbeat"
	AgentService_ReportEvents_FullMethodName   = "/edr.v1.AgentService/ReportEvents"
	AgentService_SyncPolicy_FullMethodName     = "/edr.v1.AgentService/SyncPolicy"
	AgentService_ExecuteCommand_FullMethodName = "/edr.v1.AgentService/ExecuteCommand"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Heartbeat Agent 心跳上报 (一元 RPC)
	// 用途: 维持连接、上报状态、获取配置版本
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// ReportEvents Agent 批量上报安全事件 (客户端流)
	// 用途: 流式上传事件数据，支持大批量传输
	ReportEvents(ctx context.Context, opts ...grpc.CallOption) (AgentService_ReportEventsClient, error)
	// SyncPolicy 策略同步 (服务端流)
	// 用途: Agent 拉取最新检测策略
	SyncPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (AgentService_SyncPolicyClient, error)
	// ExecuteCommand 命令执行通道 (双向流)
	// 用途: 云端命令下发与 Agent 结果回传
	ExecuteCommand(ctx context.Context, opts ...grpc.CallOption) (AgentService_ExecuteCommandClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportEvents(ctx context.Context, opts ...grpc.CallOption) (AgentService_ReportEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReportEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceReportEventsClient{stream}
	return x, nil
}

type AgentService_ReportEventsClient interface {
	Send(*EventBatch) error
	CloseAndRecv() (*ReportResponse, error)
	grpc.ClientStream
}

type agentServiceReportEventsClient struct {
	grpc.ClientStream
}

func (x *agentServiceReportEventsClient) Send(m *EventBatch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceReportEventsClient) CloseAndRecv() (*ReportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) SyncPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (AgentService_SyncPolicyClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_SyncPolicy_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceSyncPolicyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_SyncPolicyClient interface {
	Recv() (*PolicyUpdate, error)
	grpc.ClientStream
}

type agentServiceSyncPolicyClient struct {
	grpc.ClientStream
}

func (x *agentServiceSyncPolicyClient) Recv() (*PolicyUpdate, error) {
	m := new(PolicyUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, opts ...grpc.CallOption) (AgentService_ExecuteCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_ExecuteCommand_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceExecuteCommandClient{stream}
	return x, nil
}

type AgentService_ExecuteCommandClient interface {
	Send(*CommandResult) error
	Recv() (*Command, error)
	grpc.ClientStream
}

type agentServiceExecuteCommandClient struct {
	grpc.ClientStream
}

func (x *agentServiceExecuteCommandClient) Send(m *CommandResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceExecuteCommandClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// Heartbeat Agent 心跳上报 (一元 RPC)
	// 用途: 维持连接、上报状态、获取配置版本
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// ReportEvents Agent 批量上报安全事件 (客户端流)
	// 用途: 流式上传事件数据，支持大批量传输
	ReportEvents(AgentService_ReportEventsServer) error
	// SyncPolicy 策略同步 (服务端流)
	// 用途: Agent 拉取最新检测策略
	SyncPolicy(*PolicyRequest, AgentService_SyncPolicyServer) error
	// ExecuteCommand 命令执行通道 (双向流)
	// 用途: 云端命令下发与 Agent 结果回传
	ExecuteCommand(AgentService_ExecuteCommandServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) ReportEvents(AgentService_ReportEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedAgentServiceServer) SyncPolicy(*PolicyRequest, AgentService_SyncPolicyServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncPolicy not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteCommand(AgentService_ExecuteCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportEvents(&agentServiceReportEventsServer{stream})
}

type AgentService_ReportEventsServer interface {
	SendAndClose(*ReportResponse) error
	Recv() (*EventBatch, error)
	grpc.ServerStream
}

type agentServiceReportEventsServer struct {
	grpc.ServerStream
}

func (x *agentServiceReportEventsServer) SendAndClose(m *ReportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceReportEventsServer) Recv() (*EventBatch, error) {
	m := new(EventBatch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_SyncPolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PolicyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).SyncPolicy(m, &agentServiceSyncPolicyServer{stream})
}

type AgentService_SyncPolicyServer interface {
	Send(*PolicyUpdate) error
	grpc.ServerStream
}

type agentServiceSyncPolicyServer struct {
	grpc.ServerStream
}

func (x *agentServiceSyncPolicyServer) Send(m *PolicyUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_ExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ExecuteCommand(&agentServiceExecuteCommandServer{stream})
}

type AgentService_ExecuteCommandServer interface {
	Send(*Command) error
	Recv() (*CommandResult, error)
	grpc.ServerStream
}

type agentServiceExecuteCommandServer struct {
	grpc.ServerStream
}

func (x *agentServiceExecuteCommandServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceExecuteCommandServer) Recv() (*CommandResult, error) {
	m := new(CommandResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edr.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportEvents",
			Handler:       _AgentService_ReportEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncPolicy",
			Handler:       _AgentService_SyncPolicy_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteCommand",
			Handler:       _AgentService_ExecuteCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "edr/v1/agent.proto",
}
